### ISSUE TITLE
Availability on Maven Central

### ISSUE THREAD

**Issue by michael-schnell** [agrison/redux4j#6]
When it finally has a lincense (#3), it would be nice to make it available on Maven Central.

**Comment by agrison** [comment]
It will be soon, I'll get back to you when it's done.

**Comment by michael-schnell** [comment]
Cool!

**Comment by agrison** [comment]
The library is now available on Maven Central: https://repo1.maven.org/maven2/me/grison/redux4j/1.0/

You can use it like this:
```xml
<dependency>
  <groupId>me.grison</groupId>
  <artifactId>redux4j</artifactId>
  <version>1.0</version>
</dependency>
```

I have updated the README accordingly.
